import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
     
      <body className="min-h-full flex flex-col">
         <div>
          <nav className="bg-gray-800 shadow-md w-full rounded">
            <div className="max-w-7xl mx-auto px-4 flex items-center justify-between h-16">Imperial & Metric Converter
              <div className="space-x-8">
                <a href="/pounds-kilograms" className="text-white hover:text-blue-600">pounds-kilograms</a>
                <a href="/kilometres-miles/miles-kilometres" className="text-white hover:text-blue-600">miles-kilometres</a>
                <a href="/farenheit-celcius" className="text-white hover:text-blue-600">farenheit-celcius</a>
              </div>
            </div>
          </nav>
          {children}
        </div>
      </body>
    </html>
  );
}
